Add workspaces for hometasks
necrifede/software-designs-and-algorithms pull request #2
Opened 2022-02-21 22:28 UTC by necrifede

configuring workspaces and adding the classes

2022-02-22 20:33 UTC, nionis99 requested changes
Looks cool, only minor comments/suggestions.

2022-02-22 20:33 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Inventory.ts
> +const compareByWeight = (itemA, itemB) => itemA.getWeight() - itemB.getWeight();
Let's make compareByValue class function while we are doing OOP task

2022-02-22 20:33 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Inventory.ts
> +        this.items.sort(compareByValue);
You can make it void w/o return by simplifying it
`
 const compare = comparator ? comparator.compare : this.compareByValue;
        this.items.sort(compare);
`

2022-02-22 20:33 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Item.ts
> +    // TODO: ask: difference between String and string
String is an object for characters like `const obj = new String('s')` the type would be object. In JS there are 7 primitive types: number, bigint, boolean, string, undefined, symbol, and null.

You should use `string` in js to represent primitive type

2022-02-22 20:33 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Item.ts
> +    constructor(name: String, value: number, weight: number) {
We need to have id in constructor also. 
Ex.:

`
this.id = counter - 1;
`

2022-02-22 20:33 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Weapon.ts
> +        const addendum = this.getDurability() <= 0 ? ' The hammer breaks.' : '';
Probably, hammer should be as `${this.getName()}`

2022-02-22 20:33 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Sword.ts
> +        this.setBaseDamage(1.25 * this.getBaseDamage());
`If the base damage of a sword were to be 100, then the maximum that the effective damage could be increased to would be 125`
Let's say we have 100 base damage , so by increasing the damageModifier we can't exceed 25% (0.25 is maximum). It is similar as with bow.

2022-02-23 06:41 UTC, necrifede commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Sword.ts
> +        this.setBaseDamage(1.25 * this.getBaseDamage());
I am not sure if I understand well, I would really need more explicit examples. please check my implementation first. thank you

2022-02-23 06:45 UTC, necrifede commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Item.ts
> +    constructor(name: String, value: number, weight: number) {
fixed :)

2022-02-23 10:18 UTC, nionis99 approved these changes
Updated to 5

2022-02-23 10:18 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/ValueComparator.ts
> +}
You could just add compareByValue function in inventory, which won't create new instance all the time you want to sort by value

2022-02-23 10:18 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Item.ts
> +    constructor(name: String, value: number, weight: number) {
We need both. Id and counter to be increased. id should start from 0. For now your id will be 1 all the time, while counter is 0, doesn't it ?

2022-02-23 10:26 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Sword.ts
> +        this.setBaseDamage(1.25 * this.getBaseDamage());
Let's say our baseDamage is 100, primary damage modifier is 10 and our modifier change rate is 10.
We will polish Sword 3 times. We will get modifier 30 which is already more then 25% of base damage. We don't need to set baseDamage here. We are only updating damage modifier up to 25% of base damage.

2022-02-23 10:36 UTC, nionis99 commented on docs/1-building-blocks-of-oop-part-1/hometask/src/Sword.ts
> +        const polishedDamageModifier = this.getDamageModifier() + Weapon.MODIFIER_CHANGE_RATE;
Example of how i understood it.

```
// We are checking polishedDmgModifier
const polishedDamageModifier = this.getDamageModifier() + Weapon.MODIFIER_CHANGE_RATE;
// Maximum modifier what we should polish up to
const maximumDamageModifier = this.getDamageModifier() * 0.25;
// If we exceeded it we capping it up to maximum, otherwise we polishing it as it is
const newDamageModifier =
polishedDamageModifier >= maximumDamageModifier
? maximumDamageModifier
: polishedDamageModifier;
// setting polished modifier
this.setDamageModifier(newDamageModifier);
```

2022-03-01 11:23 UTC, merged